concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main, develop ]
    paths: ['go-service/**', '.github/workflows/go-ci.yml']
  pull_request:
    branches: [ main, develop ]
    paths: ['go-service/**', '.github/workflows/go-ci.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-service
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true
        
    - name: Verify dependencies
      run: go mod verify
      
    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...
      
    - name: Build application
      run: go build -v ./ %     